workflows:
  android-release:
    name: Android Release Build
    instance_type: linux
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.mmorpg.mobile"
        APP_NAME: "MMORPG Mobile"
    triggering:
      events:
        - push
    scripts:
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - thawannerickc.marques@gmail.com
        notify:
          success: true
          failure: true
